### PR TITLE
WIP - Blog Post - Recap: TypeScript Editor Shootout

### PR DESCRIPTION
**Pull request by kenhowardpdx**
@smashdevcode @chalkers @adron 

Fork this branch and PR into it with your editor recap. Once I have all the recaps I'll put together the conclusion and we can discuss.

### CODE REVIEW

**Comment by Adron** [comment]
Fooey, I just did a whole write up and submitted a PR. Hope that's ok. I for some reason missed this stubbed file. Looks good though.  Let me know when you add the recap to the typescript page and I'll add a link on my own blog entry.

**Comment by kenhowardpdx** [comment]
@Adron The complete write up is cool too. This is just a recap that shows a brief summary of each of the editors. We can link to your complete review from this post. :smile: Can you give me something for "The Good" and "The Bad"?

**Comment by kenhowardpdx** [comment]
@Adron @smashdevcode @chalkers -- Any chance we can get a couple of paragraphs to help this poor little article? If not, I'll trash this little guy.

**Comment by chalkers** [comment]
Added my input on #6

**Comment by kenhowardpdx** [comment]
Closing since this is stale content.... maybe we'll revisit the idea in the next year.

**Pull request closed without merging**
